### ISSUE TITLE
In the case of ViT-B/16 (8x224), what are the FLOPs and Param of BIKE?

### ISSUE THREAD

**Issue by geek12138** [whwu95/BIKE#1]
In the case of ViT-B/16 (8x224), what are the FLOPs and Param of BIKE?

**Comment by whwu95** [comment]
For ViT-B/16 (8x224) in the case of BIKE, the FLOPs are 92G, and the number of parameters (Params) is 95M.

**Comment by geek12138** [comment]
Thank you for your reply, this model is really great.
