### ISSUE TITLE
Lack of file (K400_val_vit_L14_attributes.json)

### ISSUE THREAD

**Issue by c747903646** [whwu95/BIKE#12]
Hello! 

I have not found the necessary file "lists/k400/K400_val_vit_L14_attributes.json" that is written in "k400_train_video_attr_vitb-32-f8.yaml".

Can you upload the file? Thanks!

**Comment by whwu95** [comment]
Thank you for your interest in our work.
The JSON file containing the attributes is already available at https://github.com/whwu95/BIKE/releases/tag/v1.0. We have provided the training code for the attribute branch, which can be referenced at https://github.com/whwu95/BIKE/blob/main/train_attributes.py. The validation section in this code can be easily modified to serve as the test code.
