### ISSUE TITLE
Frozen label encoder

### ISSUE THREAD

**Issue by Liu-arch** [whwu95/BIKE#13]
What is the difference and connection between Frozen label encoder and category encoder, I see in table6(a) it shows that adding frozen label encoder improves the result. And what is (technical) Transf?

**Comment by Liu-arch** [comment]
In addition to this in exps/k400/VIT-B/32/8f/video_attributes_log.txt why is the best test accuracy only 70.05050502892696. and under that folder write a==0.7 b==0.3 top1==81.46969604492188 top5==95.8131332397461. So for VIT-B/32/8f can we achieve 81.46 accuracy?

**Comment by whwu95** [comment]
You may have a misunderstanding. In table 6(a), "frozen label encoder" refers to freezing the label encoder, rather than adding a new "frozen label encoder" component. (technical) "Transf" refers to adding additional temporal transformer layers after ViT (Vision Transformer).
