### ISSUE TITLE
Questions about the pre-generated attributes

### ISSUE THREAD

**Issue by bedman367** [whwu95/BIKE#2]
Congratulation to your excellent work!  It seems that current published code doesn't include the 'pre-generated attributes' which should be in a json file ,  and I also find that the test code doesn't include the attributes branch now. I wonder that will the complete code be published soon ?

**Comment by whwu95** [comment]
Thank you for your interest in our work.
The JSON file containing the attributes is already available at https://github.com/whwu95/BIKE/releases/tag/v1.0. We have provided the training code for the attribute branch, which can be referenced at https://github.com/whwu95/BIKE/blob/main/train_attributes.py. The validation section in this code can be easily modified to serve as the test code.
