### ISSUE TITLE
num_sample=1——>4

### ISSUE THREAD

**Issue by Liu-arch** [whwu95/BIKE#9]
When changing num_sample from 1 to 4, how is the function in train modified: in particular, the following code
`images = images.view((-1,config.data.num_segments,3)+images.size()[-2:])  # bt 3 h w
 b,t,c,h,w = images.size()
images= images.view(-1,c,h,w)`
and
`image_embedding, cls_embedding, text_embedding, logit_scale = model(images, texts, return_token=True)`
After the incoming parameters of the model are changed from a tensor to a list

**Comment by Liu-arch** [comment]
Did you provide the lists/k400/K400_train_vit_L14_attributes.json file that attributes_train_path refers to? ;Other than that, is the model after training video brand and then attributes ready to be used as the final model?

**Comment by whwu95** [comment]
> When changing num_sample from 1 to 4, how is the function in train modified: in particular, the following code `images = images.view((-1,config.data.num_segments,3)+images.size()[-2:]) # bt 3 h w b,t,c,h,w = images.size() images= images.view(-1,c,h,w)` and `image_embedding, cls_embedding, text_embedding, logit_scale = model(images, texts, return_token=True)` After the incoming parameters of the model are changed from a tensor to a list

Don't change the num_sample, just set it to 1.

**Comment by whwu95** [comment]
> Did you provide the lists/k400/K400_train_vit_L14_attributes.json file that attributes_train_path refers to? ;Other than that, is the model after training video brand and then attributes ready to be used as the final model?

For VIT-L model, we are not going to provide attributes json.

**Comment by Liu-arch** [comment]
What about the VIT-B model



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Wenhao ***@***.***&gt;; 
发送时间: 2023年10月13日(星期五) 上午9:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [whwu95/BIKE] num_sample=1——&gt;4 (Issue #9)





  
Did you provide the lists/k400/K400_train_vit_L14_attributes.json file that attributes_train_path refers to? ;Other than that, is the model after training video brand and then attributes ready to be used as the final model?
  
For VIT-L model, we are not going to provide attributes json.
